/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadoravectores.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

res_v *
suma_vectores_1(vectores arg1,  CLIENT *clnt)
{
	static res_v clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SUMA_VECTORES,
		(xdrproc_t) xdr_vectores, (caddr_t) &arg1,
		(xdrproc_t) xdr_res_v, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
