/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadoravectores.h"
#include <stdio.h>
#include <stdlib.h>
#define TAM_MAX 255

void
calculadora_vectores(char *host, vectores u)
{
	CLIENT *clnt;
	res_v  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORAVECTORESV1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    result_1 = suma_vectores_1(u, clnt);
    if (result_1 == (res_v *) NULL) {
        clnt_perror (clnt, "call failed");
    }

    printf("\n-----------------------------------------\nEl resultado de la suma de vectores es: ");
    printf("(");
    for(int i=0; i< result_1->v.v_len; ++i)
        printf("%lf , ", result_1->v.v_val[i]);

    printf(")\n");

    free(result_1->v.v_val);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];


    int tam;
    vectores u;

        printf("Tamaño de los vectores:");
        scanf("%d", &tam);

    u.v1.v1_len= tam;
    u.v2.v2_len= tam;
    u.v1.v1_val= malloc(sizeof(double) * tam);
    u.v2.v2_val= malloc(sizeof(double) * tam);

    printf("\tElementos del primer Vector:\n");

    for(int i=0; i< tam; ++i){
        printf("\tInserte el elemento [%d]:\t", i);
        scanf("%lf", &u.v1.v1_val[i]);
    }

    printf("\tElementos del segundo Vector:\n");

    for(int i=0; i< tam; ++i){
        printf("\tInserte el elemento [%d]:\t", i);
        scanf("%lf", &u.v2.v2_val[i]);
    }

    calculadora_vectores(host, u);
    free(u.v1.v1_val);
    free(u.v2.v2_val);

exit (0);
}
