/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORAVECTORES_H_RPCGEN
#define _CALCULADORAVECTORES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct vectores {
	struct {
		u_int v1_len;
		double *v1_val;
	} v1;
	struct {
		u_int v2_len;
		double *v2_val;
	} v2;
};
typedef struct vectores vectores;

struct res_v {
	struct {
		u_int v_len;
		double *v_val;
	} v;
};
typedef struct res_v res_v;

#define CALCULADORA 0x20000001
#define CALCULADORAVECTORESV1 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA_VECTORES 1
extern  res_v * suma_vectores_1(vectores , CLIENT *);
extern  res_v * suma_vectores_1_svc(vectores , struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA_VECTORES 1
extern  res_v * suma_vectores_1();
extern  res_v * suma_vectores_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vectores (XDR *, vectores*);
extern  bool_t xdr_res_v (XDR *, res_v*);

#else /* K&R C */
extern bool_t xdr_vectores ();
extern bool_t xdr_res_v ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORAVECTORES_H_RPCGEN */
