/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdlib.h>

void
calculadora_1(char *host, componentes x, char operador)
{
	CLIENT *clnt;
	double  *result;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORAV1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    switch(operador) {
        case '+':
            result = sumar_1(x, clnt);
            if (result == (double *) NULL) {
                clnt_perror (clnt, "call failed suma");
            }
            break;

        case '-':
            result = resta_1(x, clnt);
            if (result == (double *) NULL) {
                clnt_perror (clnt, "call failed resta");
            }
            break;

        case 'x':
            result = multiplicar_1(x, clnt);
            if (result == (double *) NULL) {
                clnt_perror (clnt, "call failed multiplicacion");
            }
            break;

        case '/':
            if(x.b!=0)
                result = dividir_1(x, clnt);
            else
                printf("\tError: Division entre 0\n");

            if (result == (double *) NULL) {
                clnt_perror (clnt, "call failed division");
            }
            break;
	    default:
	        printf("No se reconoce este operador. Solamente son validos: \t+\t-\tx\t/");
	        break;

    }

            printf("\tEl resultado es: %lf\n", *result);



#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{

	char *host;
    char operador;
    componentes x;

	if (argc != 5) {
		printf ("usage: %s server_host (componente1 operador componente)\nOperadores:\t+\t-\tx\t/", argv[0]);
		exit (1);
	}

	host = argv[1];

    x.a= atof(argv[2]);
    operador= *argv[3];
    x.b= atof(argv[4]);

	calculadora_1 (host, x, operador);

exit (0);
}
